// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#pragma once

#include "/Engine/Public/Platform.ush"

void MainVS(
	in float4 InPosition : ATTRIBUTE0, 
	in float2 InUV : ATTRIBUTE1,
	out float2 OutUV : TEXCOORD0, 
	out float4 OutPosition : SV_POSITION
)
{
	OutPosition = InPosition;
	OutUV = InUV;
}